version: '2'
volumes:
  sense-data:
  app-logs:
services:
  influxdb:
    restart: always
    build: ./influxdb
    ports:
      - "8086"
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
  sensor:
    build: ./sensor
    privileged: true
    restart: always
    volumes:
      - 'sense-data:/data'
  telegraf:
    build: ./telegraf
    restart: always

  sdshare:
    build: ./sdshare
    container_name: sdshare
    privileged: true
    network_mode: "host"
    ports:
      - "47546"
    volumes:
      - "app-logs:/applogs"
    environment:
      - APP_NAME=BalenaSense
      - APP_VERSION=1.0.0
      - APP_WEB_PORT=80
      - APP_LOG_PATH=/applogs
      - REST_ADDRESS=0.0.0.0
      - REST_PORT=47546
      - ETH_DISABLE=1
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'
      io.resin.update.strategy: download-then-kill
